enum AdPPPP{
  kztym_launch,
  kztym_int_spin_step,
  kztym_rv_double_claim,
  kztym_rv_double_only,
  kztym_int_step,
  kztym_rv_magic_gold,
  kztym_rv_claim_answer,
  kztym_rv_open_box,
  kztym_int_box_continue,
  kztym_int_spin_go,
  kztym_rv_claim_spin,
  kztym_int_close_spin,
  kztym_int_answer_continue,
  kztym_draw_watch,
  kztym_rv_sign_in,
  kztym_int_claim_spin,

  kztym_rv_task_answer,
  kztym_int_task_answer_close,
  kztym_rv_task_box,
  kztym_rv_task_box_close,
  kztym_rv_task_gold,
  kztym_rv_task_claim_spin,
  kztym_int_task_claim_spin,
  kztym_int_task_spin_go,
  kztym_int_task_close_spin,
}